/*
 * HEADERS.H
 *  Created on: 2018年8月29日
 *       Brief: 头文件、宏定义等都放这里
 */

#ifndef _HEADERS_H
#define _HEADERS_H

#define MAX_STRLEN 100

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <pin.h>
#include <soc.h>
#include <drv_gpio.h>
#include <drv_usart.h>
#include <drv_spi.h>
#include "drv_eflash.h"
#include "EIB_SPI.h"
#include "EIB_eInk.h"
#include "EIB_UART.h"
#include "EIB_8266command.h"

#endif
